# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: bionic

language: R
cache: packages


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx

script:
- Rscript -e "if (!requireNamespace('devtools', quietly = TRUE)) install.packages(c('devtools', 'remotes'), repos  = 'https://cloud.r-project.org', quiet = TRUE)"
# for which_last
- Rscript -e "if (!requireNamespace('hutilscpp', quietly = TRUE) || packageVersion('hutilscpp') < '0.4.0') remotes::install_github('hughparsonage/hutilscpp', quick = FALSE, args = '')"
- Rscript -e "devtools::install(quiet = TRUE)"
- R CMD build .
- travis_wait 25 R CMD check *tar.gz --no-manual

after_success:
    - travis_wait 45 Rscript -e 'covr::codecov()'
