# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: bionic

language: R
latex: false
pandoc: false
cache: packages


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx

install:
- R -e 'devtools::install_deps(dep = TRUE)'

script:
- R CMD build .
- travis_wait 30 R CMD check *tar.gz
