# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: bionic

language: R
cache: packages


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
