# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distr2status <- function(N, dead, healed, active, critical) {
    .Call(`_covid19_model_sa2_distr2status`, N, dead, healed, active, critical)
}

#' @name do_1day_supermarket
#' @description Simulate the experience of everyone's interactions
#' at supermarkets in a single day
#' @param Status \code{integer(N)}: Whether each individual is infected or not etc.
#' @param InfectedOn The day on which the individual was infected.
#' @param SA2 The 2016 SA2 code of each individual. Must be sorted.
#' @param Age The age of every individual.
#' @param Employment Information about employment of each individual.
#' @param SupermarketTarget The supermarket that the person visits,
#' equal to zero for each individual who doesn't visit a supermarket.
#' @param Resistance For each individual, inherent resistance to being infected.
#' @param N \code{int} Population of Australia.
#' @param check_sa2_key \code{bool} Whether to check SA2 is sorted, defaults to \code{true}.
#' @param returner Used to return other elements. By default 0, i.e. just return Status.
#' @param r0_supermarket The reproduction rate of infection in each supermarket, without
#' including resistance.
#' @param resistance1 Resistance parameter 1: the threshold below which
#' an infection takes place.
#' @param resistance2 Reistance parameter 2: used with Age to increase
#' the likelihood of both critical and active cases among the elderly.
#' @noRd
NULL

status_killed <- function() {
    .Call(`_covid19_model_sa2_status_killed`)
}

status_healed <- function() {
    .Call(`_covid19_model_sa2_status_healed`)
}

status_suscep <- function() {
    .Call(`_covid19_model_sa2_status_suscep`)
}

status_nosymp <- function() {
    .Call(`_covid19_model_sa2_status_nosymp`)
}

status_insymp <- function() {
    .Call(`_covid19_model_sa2_status_insymp`)
}

status_critic <- function() {
    .Call(`_covid19_model_sa2_status_critic`)
}

supermarket_weekday_hrs <- function() {
    .Call(`_covid19_model_sa2_supermarket_weekday_hrs`)
}

supermarket_weekend_hrs <- function() {
    .Call(`_covid19_model_sa2_supermarket_weekend_hrs`)
}

test_array4k <- function(w, x, y, z, nw, nx, ny, nz) {
    .Call(`_covid19_model_sa2_test_array4k`, w, x, y, z, nw, nx, ny, nz)
}

do_rep <- function(r, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_rep`, r, nThread)
}

do_au_simulate <- function(StatusOriginal, InfectedOnOriginal, SA2, hid, Age, School, DZN, wid, nColleagues, PlaceTypeBySA2, LabourForceStatus, SeedOriginal, Policy, nPlacesByDestType, Epi, Incubation, Illness, nSupermarketsAvbl, SupermarketTypical, minPlaceID_nPlacesByDestType, yday_start, days_to_sim, N, display_progress = TRUE, on_terminal = FALSE, by_state = TRUE, returner = 0L, console_width = 80L, optionz = 0L, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_au_simulate`, StatusOriginal, InfectedOnOriginal, SA2, hid, Age, School, DZN, wid, nColleagues, PlaceTypeBySA2, LabourForceStatus, SeedOriginal, Policy, nPlacesByDestType, Epi, Incubation, Illness, nSupermarketsAvbl, SupermarketTypical, minPlaceID_nPlacesByDestType, yday_start, days_to_sim, N, display_progress, on_terminal, by_state, returner, console_width, optionz, nThread)
}

do_exp_dbl2int <- function(x, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_exp_dbl2int`, x, nThread)
}

do_lag_int <- function(s, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_lag_int`, s, nThread)
}

do_seqN_N <- function(hid, pid, check_hid_sorted = TRUE) {
    .Call(`_covid19_model_sa2_do_seqN_N`, hid, pid, check_hid_sorted)
}

get_nColleagues <- function(nr, N, LabourForceStatus, nThread = 1L, c_d = 0L, beta = 27, mu = 2.2, sigma = 0.62) {
    .Call(`_covid19_model_sa2_get_nColleagues`, nr, N, LabourForceStatus, nThread, c_d, beta, mu, sigma)
}

wid_supremum <- function() {
    .Call(`_covid19_model_sa2_wid_supremum`)
}

do_workplaces <- function(AusByDZN, nThread = 1L, c_d = 0L, beta = 15, mu = 2.2, sigma = 0.62) {
    .Call(`_covid19_model_sa2_do_workplaces`, AusByDZN, nThread, c_d, beta, mu, sigma)
}

testOpenmp <- function(x, nThread = 1L) {
    .Call(`_covid19_model_sa2_testOpenmp`, x, nThread)
}

count_by_sa2_age_status <- function(Group1, Group2, Group3, nThread = 1L) {
    .Call(`_covid19_model_sa2_count_by_sa2_age_status`, Group1, Group2, Group3, nThread)
}

postcode_to_sa2_sorted <- function(postcode, POSTCODE, SA2_MAINCODE) {
    .Call(`_covid19_model_sa2_postcode_to_sa2_sorted`, postcode, POSTCODE, SA2_MAINCODE)
}

punif_int <- function(n, a, b, nThread = 1L) {
    .Call(`_covid19_model_sa2_punif_int`, n, a, b, nThread)
}

dqsample_int2 <- function(m, n) {
    .Call(`_covid19_model_sa2_dqsample_int2`, m, n)
}

prlnorm_dbl <- function(n, a, b, nThread = 1L) {
    .Call(`_covid19_model_sa2_prlnorm_dbl`, n, a, b, nThread)
}

prlnorm_int <- function(n, a, b, nThread = 1L) {
    .Call(`_covid19_model_sa2_prlnorm_int`, n, a, b, nThread)
}

prcauchy <- function(n, a, b, nThread = 1L) {
    .Call(`_covid19_model_sa2_prcauchy`, n, a, b, nThread)
}

do_lemire_rand <- function(n, S) {
    .Call(`_covid19_model_sa2_do_lemire_rand`, n, S)
}

do_lemire_rand_par <- function(n, S, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_lemire_rand_par`, n, S, nThread)
}

lemire_char <- function(N, p, S, return_early = 0L, nThread = 1L) {
    .Call(`_covid19_model_sa2_lemire_char`, N, p, S, return_early, nThread)
}

cf_sample <- function(n, m, x, S) {
    .Call(`_covid19_model_sa2_cf_sample`, n, m, x, S)
}

cf_mod_lemire <- function(n, p, S, m = 0L, nThread = 1L) {
    .Call(`_covid19_model_sa2_cf_mod_lemire`, n, p, S, m, nThread)
}

RCauchy <- function(U, location, scale, nThread = 1L) {
    .Call(`_covid19_model_sa2_RCauchy`, U, location, scale, nThread)
}

short_sa2 <- function(sa2) {
    .Call(`_covid19_model_sa2_short_sa2`, sa2)
}

shorten_sa2s_ordered <- function(SA2) {
    .Call(`_covid19_model_sa2_shorten_sa2s_ordered`, SA2)
}

sa2_firsts_finals <- function(SA2, nsa2 = 2310L, is_state = FALSE) {
    .Call(`_covid19_model_sa2_sa2_firsts_finals`, SA2, nsa2, is_state)
}

do_minmax_par <- function(x, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_minmax_par`, x, nThread)
}

do_ModuloIndex <- function(x, mod, max, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_ModuloIndex`, x, mod, max, nThread)
}

do_modulo_d <- function(x, m, divisor, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_modulo_d`, x, m, divisor, nThread)
}

do_modulo_16 <- function(x, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_modulo_16`, x, nThread)
}

do_lag_in_place <- function(x) {
    .Call(`_covid19_model_sa2_do_lag_in_place`, x)
}

do_pminCppp <- function(x, a = 0L, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_pminCppp`, x, a, nThread)
}

do_is_unsorted_pint <- function(x, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_is_unsorted_pint`, x, nThread)
}

