# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distr2status <- function(N, dead, healed, active, critical) {
    .Call(`_covid19_model_sa2_distr2status`, N, dead, healed, active, critical)
}

#' @name do_1day_supermarket
#' @description Simulate the experience of everyone's interactions
#' at supermarkets in a single day
#' @param Status \code{integer(N)}: Whether each individual is infected or not etc.
#' @param InfectedOn The day on which the individual was infected.
#' @param SA2 The 2016 SA2 code of each individual. Must be sorted.
#' @param Age The age of every individual.
#' @param Employment Information about employment of each individual.
#' @param SupermarketTarget The supermarket that the person visits,
#' equal to zero for each individual who doesn't visit a supermarket.
#' @param Resistance For each individual, inherent resistance to being infected.
#' @param N \code{int} Population of Australia.
#' @param check_sa2_key \code{bool} Whether to check SA2 is sorted, defaults to \code{true}.
#' @param returner Used to return other elements. By default 0, i.e. just return Status.
#' @param r0_supermarket The reproduction rate of infection in each supermarket, without
#' including resistance.
#' @param resistance1 Resistance parameter 1: the threshold below which
#' an infection takes place.
#' @param resistance2 Reistance parameter 2: used with Age to increase
#' the likelihood of both critical and active cases among the elderly.
#' @noRd
NULL

status_killed <- function() {
    .Call(`_covid19_model_sa2_status_killed`)
}

status_healed <- function() {
    .Call(`_covid19_model_sa2_status_healed`)
}

status_suscep <- function() {
    .Call(`_covid19_model_sa2_status_suscep`)
}

status_nosymp <- function() {
    .Call(`_covid19_model_sa2_status_nosymp`)
}

status_insymp <- function() {
    .Call(`_covid19_model_sa2_status_insymp`)
}

status_critic <- function() {
    .Call(`_covid19_model_sa2_status_critic`)
}

do_max_par_int <- function(x, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_max_par_int`, x, nThread)
}

do_au_simulate <- function(Status, InfectedOn, SA2, State, hid, seqN, HouseholdSize, Age, School, PlaceTypeBySA2, Employment, Resistance, Policy, nPlacesByDestType, FreqsByDestType, Epi, nSupermarketsAvbl, SupermarketTypical, SupermarketHour, yday_start, days_to_sim, N = 25e6L, display_progress = TRUE, by_state = TRUE, console_width = 80L, optionz = 0L, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_au_simulate`, Status, InfectedOn, SA2, State, hid, seqN, HouseholdSize, Age, School, PlaceTypeBySA2, Employment, Resistance, Policy, nPlacesByDestType, FreqsByDestType, Epi, nSupermarketsAvbl, SupermarketTypical, SupermarketHour, yday_start, days_to_sim, N, display_progress, by_state, console_width, optionz, nThread)
}

do_exp_dbl2int <- function(x, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_exp_dbl2int`, x, nThread)
}

do_lag_int <- function(s, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_lag_int`, s, nThread)
}

do_seqN_N <- function(hid, pid, check_hid_sorted = TRUE) {
    .Call(`_covid19_model_sa2_do_seqN_N`, hid, pid, check_hid_sorted)
}

testOpenmp <- function(x, nThread = 1L) {
    .Call(`_covid19_model_sa2_testOpenmp`, x, nThread)
}

punif_int <- function(n, a, b, nThread = 1L) {
    .Call(`_covid19_model_sa2_punif_int`, n, a, b, nThread)
}

dqsample_int2 <- function(m, n) {
    .Call(`_covid19_model_sa2_dqsample_int2`, m, n)
}

prlnorm_dbl <- function(n, a, b, nThread = 1L) {
    .Call(`_covid19_model_sa2_prlnorm_dbl`, n, a, b, nThread)
}

prlnorm_int <- function(n, a, b, nThread = 1L) {
    .Call(`_covid19_model_sa2_prlnorm_int`, n, a, b, nThread)
}

prcauchy <- function(n, a, b, nThread = 1L) {
    .Call(`_covid19_model_sa2_prcauchy`, n, a, b, nThread)
}

lemire_rand <- function(n, d, s32, nThread = 1L, q2 = 0L) {
    .Call(`_covid19_model_sa2_lemire_rand`, n, d, s32, nThread, q2)
}

short_sa2 <- function(sa2) {
    .Call(`_covid19_model_sa2_short_sa2`, sa2)
}

shorten_sa2s_ordered <- function(SA2) {
    .Call(`_covid19_model_sa2_shorten_sa2s_ordered`, SA2)
}

do_minmax_par <- function(x, nThread = 10L) {
    .Call(`_covid19_model_sa2_do_minmax_par`, x, nThread)
}

do_ModuloIndex <- function(x, d, m, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_ModuloIndex`, x, d, m, nThread)
}

do_modulo_d <- function(x, m, d, nThread = 1L) {
    .Call(`_covid19_model_sa2_do_modulo_d`, x, m, d, nThread)
}

do_is_unsorted_pint <- function(x) {
    .Call(`_covid19_model_sa2_do_is_unsorted_pint`, x)
}

